### PR TITLE
Performance Improvements, Translation Support

### PR DESCRIPTION
**Pull request by bhubbard**
Hey guys, so here is my first commit. The changes are as follows:

* Improved the uninstall code
* Optimized images
* Fixed several CSS issues, then minified and moved into an assets directory
* Improved Github Readme
* Moved all files to top directory of the github repo, I also suggest renaming it. The yoast plugin is a good example of managing a WordPress plugin on github.

### CODE REVIEW

**Comment by bhubbard** [comment]
Hey IDX Broker team, I already emailed you about this, but I thought to ping you all here as well.

@bauski @antonioortegajr @sheparddw @MissEmilee

Anyone else I miss? You should all be listed in the IDX Broker Organization.

To keep anyone else updated, I know the commits in this pull request are a bit messy, but I have tested all of my changes. There is one bug I was aware of which exists in the current version of the plugin before any of my commits, and still needs to be fixed:

Issue #1 

Mainly my changes provide a performance boost, re-organizes some of the code, and gets things better inline for me to start integrating many of the features I presented at the IDX Dev Summit. 

I would love to see other IDX Broker Partners/Devs get involved and test the code as well or start contributing, any takers?

@chadajohnson @davebonds @isensmith @deevoweb @AlphaBlossom others?

**Comment by AlphaBlossom** [comment]
Hey @bhubbard, thanks for all of your hard work on this. I am pretty git illiterate at this point, but I'll try to contribute.

I have a couple things, but I'll confirm on my local and then I'll add them here.

**Comment by bhubbard** [comment]
Ok, I found one bug remaining, I thought I fixed it but maybe @sheparddw can take a look. When activating the plugin I get the following error message: 

https://www.evernote.com/shard/s1/sh/98ba8126-bd05-4a08-b825-1402a70937be/0782679d9a3b35c7/res/67c9bd96-f7d5-471f-9b6f-f0a17799c300/skitch.png?resizeSmall&width=832

This file appears to be the cause:

https://github.com/bhubbard/wordpress-plugin/blob/master/omnibar/idx-omnibar-get-locations.php#L24

**Comment by sheparddw** [comment]
I am completely restructuring the plugin files to be more PSR-2 compliant.
This overhaul I am working on will be the 1.2.2 update.
The next update after that will likely restructure the UI and simplify the whole integration process.
You might want to hold off working much on this until then as there are many major changes in progress in the next few updates. These updates fix many of these issues you mentioned.
I will look into adding some of these additions you have worked on into a future update.
We appreciate the work you have put into this and look forward to your contribution after these major updates.

**Comment by bhubbard** [comment]
@sheparddw  What's the timeline for this update? Can you put it on github so others can get involved?  I take it you are using phpcs to evaluate the files?

**Comment by sheparddw** [comment]
This update is currently going through QA. We are working on synchronizing our work with Github soon.
Yes.

**Pull request closed without merging**
